# Generated by Django 5.1.3 on 2024-12-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_name', models.CharField(max_length=255)),
                ('licence_plate', models.CharField(max_length=11)),
                ('driver_name', models.CharField(max_length=50)),
                ('passenger_capacity', models.PositiveIntegerField()),
                ('car_model', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
